version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lowery_exam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/lowery_exam?schema=public"
      ADMIN_EMAIL: "harsh@in2ccq.com"
      ADMIN_PASSWORD: "Harsh@1234"
      NEXTAUTH_SECRET: "your-secret-key-change-in-production"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

volumes:
  postgres_data:
